FROM golang:1.26-alpine AS builder

WORKDIR /go/src/github.com/ory/oathkeeper

RUN apk add --no-cache build-base

COPY go.mod go.mod
COPY go.sum go.sum
COPY oryx/go.mod oryx/go.mod
COPY oryx/go.sum proto/go.sum

ENV CGO_ENABLED=0

RUN go mod download

COPY . .

RUN go build -o /usr/bin/oathkeeper .

#########################

FROM alpine:3.21

RUN addgroup -S ory \
    && adduser -S ory -G ory -D -H -s /bin/nologin \
    && apk --no-cache --update-cache --upgrade add ca-certificates tzdata

COPY --from=builder /usr/bin/oathkeeper /usr/bin/oathkeeper

USER ory

EXPOSE 4455
EXPOSE 4456

ENTRYPOINT ["oathkeeper"]
CMD ["serve"]
